Add myself Gianni Cecchetto to the list of students
heig-vd-dai-course/.github pull request #113
Opened 2024-09-20 09:22 UTC by GianniCecchetto

Closes #105

2024-09-20 09:23 UTC, GeraudSilvestri requested changes
It seems you haven't signed your commit? Can you please check that it is enabled, working and update the current PR?

2024-09-23 11:47 UTC, ludelafo approved these changes

2024-09-23 11:51 UTC, ludelafo requested changes
It seems your commits cannot be verified. Please ensure you have added a **signing key** to your GitHub settings as mentioned in the course material: <https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md#add-a-new-ssh-signing-key-to-your-github-account>.

2024-09-23 12:15 UTC, GianniCecchetto commented
My commits are now verified.

2024-09-24 14:54 UTC, GeraudSilvestri approved these changes

2024-09-24 15:03 UTC, ludelafo approved these changes

2024-09-24 15:04 UTC, merged