Add myself to the list of students
heig-vd-dai-course/.github pull request #37
Opened 2023-09-19 15:00 UTC by gwendalpiemonte

2023-09-20 05:40 UTC, hadrylouis approved these changes

2023-09-20 05:40 UTC, hadrylouis commented
Could you please add a comment with the link to your issue with #xxx
You can follow the [create a pull request](https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md#create-a-pull-request) section of the course material

2023-09-20 07:15 UTC, gwendalpiemonte commented
it's done ! @hadrylouis

2023-09-20 12:31 UTC, hadrylouis requested changes

2023-09-20 12:31 UTC, hadrylouis commented on profile/README.md
> +- Gwendal Piemontesi [@gwendalpiemonte](https://github.com/gwendalpiemonte)
It doesn't seem to be in order :)

2023-09-21 13:23 UTC, ludelafo approved these changes

2023-09-21 13:24 UTC, merged