Add Esteban GitHub username to the list of students Closes #11
heig-vd-dai-course/.github pull request #42
Opened 2023-09-19 15:14 UTC by EstebanLopezGomez

2023-09-19 15:22 UTC, EstebanLopezGomez commented
Added User

2023-09-19 15:23 UTC, EstebanLopezGomez commented
Added User @teaching-staff

2023-09-20 06:22 UTC, hadrylouis commented
It would be great if you can sign your previous commits. You can follow [this tutorial](https://stackoverflow.com/a/54987693)

2023-09-20 06:34 UTC, ludelafo requested changes

2023-09-20 06:34 UTC, ludelafo commented on profile/README.md
> -
You shouldn't have removed the line between the title and the HTML comment. Maybe it's your IDE that did format the file for you? Please re-add the lines.

2023-09-20 06:34 UTC, ludelafo commented on profile/README.md
> -
You shouldn't have removed the line between the title and the HTML comment. Maybe it's your IDE that did format the file for you? Please re-add the lines.

2023-09-20 06:34 UTC, ludelafo commented on profile/README.md
> -
You shouldn't have removed the line between the title and the HTML comment. Maybe it's your IDE that did format the file for you? Please re-add the lines.

2023-09-20 06:34 UTC, ludelafo commented on profile/README.md
> +
You left this from a previous conflict. You can remove these lines.

2023-09-20 10:24 UTC, ludelafo approved these changes

2023-09-20 10:25 UTC, merged