Add myself to the list of students
heig-vd-dai-course/.github pull request #43
Opened 2023-09-19 15:17 UTC by GuggisbergSimon

Add myself to the list of students

2023-09-20 05:42 UTC, hadrylouis commented
Could you please add a comment with the link to your issue with #xxx
You can follow the [create a pull request](https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md#create-a-pull-request) section of the course material

2023-09-21 06:25 UTC, GuggisbergSimon commented
#28

2023-09-21 07:01 UTC, ludelafo requested changes

2023-09-21 07:01 UTC, ludelafo commented on profile/README.md
> +- Simon Guggisberg [@GuggisbergSimon](https://github.com/GuggisbergSimon/)
Please add yourself to the list of students, not the teaching staff :)

2023-09-21 13:25 UTC, ludelafo approved these changes

2023-09-21 13:25 UTC, merged