Add myself (@MolinaElGringo) to the list of students
heig-vd-dai-course/.github pull request #47
Opened 2023-09-19 15:30 UTC by MolinaElGringo

Add myself (@MolinaElGringo) to the list of students

Fixes #32

2023-09-20 05:47 UTC, hadrylouis requested changes

2023-09-20 05:47 UTC, hadrylouis commented on profile/README.md
> +- Sebastian Diaz [@MolinaElGringo](https://github.com/MolinaElGringo)
Could you please add yourself in alphabetical order (by last name)

2023-09-25 07:30 UTC, MolinaElGringo commented
I should be okay now

2023-09-25 07:37 UTC, hadrylouis approved these changes

2023-09-25 07:38 UTC, merged