Add myself lucaslattion to the list of students
heig-vd-dai-course/.github pull request #56
Opened 2023-09-21 07:08 UTC by lucaslattion

Add myself lucaslattion to the list of students

2023-09-21 07:13 UTC, lucaslattion commented
Add myself (@lucaslattion ) to the list of students

2023-09-21 07:14 UTC, lucaslattion commented
@teaching-staff : Please add myself (@lucaslattion ) to the list of students

2023-09-21 07:27 UTC, lucaslattion commented
Fixes #56

2023-09-21 08:34 UTC, ludelafo requested changes
Could you sign your commits as well? You can follow the documentation here: https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md#make-changes-if-needed

2023-09-21 08:34 UTC, ludelafo commented on profile/README.md
> +- Lucas Lattion [@lucaslattion](https://github.com/lucaslattion)
Please add your name in alphabetical order by last name :)

2023-09-26 12:12 UTC, hadrylouis approved these changes

2023-09-26 12:24 UTC, merged