Add myself to the list of students
heig-vd-dai-course/.github pull request #59
Opened 2023-09-25 21:05 UTC by HumairRomain

#15

2023-09-25 21:07 UTC, HumairRomain commented
@teaching-staff

2023-09-26 07:08 UTC, ludelafo approved these changes

2023-09-26 07:10 UTC, ludelafo requested changes
You must sign your commits.

You can check the official documentation here: https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md#make-changes-if-needed

2023-09-26 12:24 UTC, HumairRomain commented
done @teaching-staff

2023-09-26 12:33 UTC, ludelafo approved these changes

2023-09-26 12:33 UTC, merged